name: Dependency Update Butler with AI Summary

on:
  schedule:
    - cron: "*/5 * * * *" # every 5 minutes
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependency: [jackson-databind, junit, maven-compiler-plugin]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Update dependency ${{ matrix.dependency }}
        run: mvn versions:use-latest-releases -Dincludes=${{ matrix.dependency }}

      - name: Commit changes for ${{ matrix.dependency }}
        id: commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            git commit -m "chore: update ${{ matrix.dependency }}"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create or update Pull Request for ${{ matrix.dependency }}
        if: steps.commit.outputs.changes == 'true'
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: "chore: update ${{ matrix.dependency }}"
          branch: dependency-update-${{ matrix.dependency }}
          title: "Dependency Update: ${{ matrix.dependency }}"
          body: "This PR updates ${{ matrix.dependency }} to the latest release."
          create-if-no-existing: true

      - name: Build and Test
        if: steps.commit.outputs.changes == 'true'
        run: mvn clean verify

      - name: Generate AI Dependency Update Summary
        if: steps.commit.outputs.changes == 'true' && steps.cpr.outputs.pull-request-number != ''
        id: ai-summary
        run: |
          UPDATED_DEPENDENCIES=$(git log -1 --pretty=format:"%s")
          SUMMARY=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -d "{
              \"model\": \"gpt-4o-mini\",
              \"messages\": [
                {\"role\": \"system\", \"content\": \"You are a helpful assistant that writes concise, clear summaries of dependency updates.\"},
                {\"role\": \"user\", \"content\": \"Generate a summary for the following dependency updates: $UPDATED_DEPENDENCIES\"}
              ]
            }" | jq -r '.choices[0].message.content')
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post AI Summary as PR Comment
        if: steps.commit.outputs.changes == 'true' && steps.cpr.outputs.pull-request-number != ''
        run: |
          gh pr comment ${{ steps.cpr.outputs.pull-request-number }} --body "${{ steps.ai-summary.outputs.summary }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
