name: Dependency Upgrade

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1" # Every Monday at 3am UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  upgrade-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Update Maven dependencies
        run: |
          mvn versions:use-latest-releases -Dincludes="com.fasterxml.jackson.core:*"
          mvn versions:use-latest-releases
          mvn versions:commit

      - name: Build & Test
        run: mvn clean install --batch-mode --update-snapshots

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git checkout -b dependency-upgrade || git checkout dependency-upgrade
            git add .
            git commit -m "chore: upgrade dependencies"
            git push origin HEAD:dependency-upgrade
          else
            echo "No dependency updates found"
          fi

      - name: Create or update PR
        if: always()
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: dependency-upgrade
          title: "chore: upgrade dependencies"
          body: "Automated dependency upgrade via GitHub Actions."
          commit-message: "chore: upgrade dependencies"
          labels: dependencies
          draft: false

      - name: Enable auto-merge
        if: always()
        run: |
          gh pr merge --auto --merge dependency-upgrade || echo "PR not found"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
